theme: jekyll-theme-slate
title: machine learning system design
description: Learn how facebook, apple, amazon, google, linkedin, snap design their machine learning system at scale.
tagline: Learn how facebook, apple, amazon, google, linkedin, snap design their machine learning system at scale. Practice machine learning system design interviews.
plugins:
  - jekyll-seo-tag
